apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.3.0
            imagePullPolicy: IfNotPresent
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: rootpasswd
            command:
            - /bin/sh
            - -c
            - mysqldump -h mysql-read -uroot -p$MYSQL_ROOT_PASSWORD --all-databases > /backup/backup-$(date +'%Y%m%d%H%M%S').sql
            volumeMounts:
            - name: backup
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: backup-mysql-pvc